from django.urls import path

from .views import (
    AccountPaymentView,
    AccountView,
    ActiveUserSubscriptionView,
    AvailableServicesView,
    СategoriesView,
    CSRFTokenView,
    DocumentView,
    MainPageView,
    NonActiveUserSubscriptionView,
    PaymentsPeriodView,
    PaymentView,
    PaymentsView,
    ServicePaymentsView,
    ServiceView,
    UserPaymentsPlanView,
    ServiceUserSubscriptionsView,
    UserSubscriptionRenewalView,
    UserSubscriptionView,
    UserSubscriptionsView,
)

urlpatterns = [
    path(
        "v1/users/<int:user_id>/main_page/",
        MainPageView.as_view(),
        name="main_page",
    ),
    path(
        "v1/users/<int:user_id>/payments/",
        PaymentsView.as_view(),
        name="payments",
    ),
    path(
        "v1/users/<int:user_id>/services/<service_id>/payment_history/",
        ServicePaymentsView.as_view(),
        name="service_payments",
    ),
    path(
        "v1/accounts/<int:account_id>/payment_history/",
        AccountPaymentView.as_view(),
        name="account_payments",
    ),
    path(
        "v1/users/account/<int:account_id>/<str:account_status>/",
        AccountView.as_view(),
        name="account_view",
    ),
    path(
        "v1/users/<int:user_id>/payment_history/<str:time_period>/",
        PaymentsPeriodView.as_view(),
        name="payments_period",
    ),
    path(
        "v1/user_subscriptions/<int:subscription_id>/",
        UserSubscriptionView.as_view(),
        name="service_payments",
    ),
    path(
        "v1/users/<int:user_id>/active/",
        ActiveUserSubscriptionView.as_view(),
        name="service_payments",
    ),
    path(
        "v1/users/<int:user_id>/nonactive/",
        NonActiveUserSubscriptionView.as_view(),
        name="service_payments",
    ),
    path(
        "v1/users/<int:user_id>/user_subscriptions/",
        UserSubscriptionsView.as_view(),
        name="service_payments",
    ),
    path(
        "v1/users/<int:user_id>/payments_plan/",
        UserPaymentsPlanView.as_view(),
        name="user_payment_plan",
    ),
    path(
        "v1/users/<int:user_id>/services/<int:service_id>/",
        ServiceUserSubscriptionsView.as_view(),
        name="service_payments",
    ),
    path(
        "v1/rules/", DocumentView.as_view(), name="rules"
    ),
    path(
        "v1/payments/<int:payment_id>/",
        PaymentView.as_view(),
        name="payment",
    ),
    path(
        "v1/token/",
        CSRFTokenView.as_view(),
        name="token",
    ),
    path(
        "v1/services/available/",
        AvailableServicesView.as_view(),
        name="available_services",
    ),
    path(
        "v1/categories/<str:category_name>/",
        СategoriesView.as_view(),
        name="categories",
    ),
    path(
        "v1/services/<str:service_name>/",
        ServiceView.as_view(),
        name="service",
    ),
    path(
        "v1/user_subscriptions/<int:user_subscription_id>/autorenewal/",
        UserSubscriptionRenewalView.as_view(),
        name="autorenewal",
    ),
]
