# Generated by Django 5.0.3 on 2024-03-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_options_alter_service_options_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='activation_method',
            field=models.IntegerField(choices=[('phone', 'Телефон'), ('email', 'Электронная почта')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='availability',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='cashback',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default=30, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=199),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
