# Generated by Django 5.0.3 on 2024-03-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_options_alter_service_options_and_more'),
        ('subscriptions', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_days', models.IntegerField(default=0, verbose_name='Срок пробного периода')),
                ('period_cost', models.IntegerField(default=0, verbose_name='Стоимость пробного периода')),
            ],
            options={
                'verbose_name': 'Пробная подписка',
                'verbose_name_plural': 'Пробные подписки',
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_method',
            field=models.CharField(choices=[('Телефон', 'Телефон'), ('Электронная почта', 'Электронная почта')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='services.service'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.trialperiod'),
        ),
    ]
