# Generated by Django 5.0.3 on 2024-03-18 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_options_alter_service_options_and_more'),
        ('subscriptions', '0003_trialperiod_alter_subscription_activation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='services.service'),
        ),
    ]
