# Generated by Django 5.0.3 on 2024-03-18 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_options_alter_service_options_and_more'),
        ('subscriptions', '0006_alter_subscription_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscription', to='services.service'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_period',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.trialperiod'),
            preserve_default=False,
        ),
    ]
