# Generated by Django 5.0.3 on 2024-03-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='subscriptions.trialperiod'),
        ),
    ]
