# Generated by Django 5.0.3 on 2024-03-18 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscription_trial_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscode',
            options={'verbose_name': 'Код доступа', 'verbose_name_plural': 'Коды доступа'},
        ),
        migrations.AddField(
            model_name='accesscode',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='name',
            field=models.CharField(default='Код доступа', max_length=50),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('activation', models.BooleanField(default=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('trial', models.BooleanField()),
                ('access_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_subscription', to='subscriptions.accesscode')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_subscription', to='subscriptions.subscription')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
            },
        ),
    ]
