# Generated by Django 5.0.3 on 2024-03-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_accesscode_options_accesscode_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'План подписки', 'verbose_name_plural': 'Планы подписки'},
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription_id',
            new_name='subscription',
        ),
    ]
