# Generated by Django 5.0.3 on 2024-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='renewal',
            field=models.BooleanField(default=False),
        ),
    ]
