# Generated by Django 5.0.3 on 2024-03-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_document_delete_payment'),
        ('subscriptions', '0010_alter_subscription_options_and_more'),
        ('users', '0010_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackApplied',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('applied_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Кэшбэк',
                'verbose_name_plural': 'Кэшбэки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.CharField(max_length=32)),
                ('account_id', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='payments', to='users.account')),
                ('cashback_applied', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='payments.cashbackapplied')),
                ('document', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='payments', to='payments.document')),
                ('user_subscription', models.ForeignKey(on_delete=models.SET('DELETED'), related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
