# Generated by Django 5.0.3 on 2024-03-18 14:47

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_cashbackapplied_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.CharField(default=payments.models.increment_receipt_number, max_length=500),
        ),
    ]
