# Generated by Django 5.0.3 on 2024-03-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_receipt'),
        ('subscriptions', '0012_alter_usersubscription_access_code_and_more'),
        ('users', '0013_account_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_id',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), related_name='account', to='users.account'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cashback_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_cashback', to='payments.cashbackapplied'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='document',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), related_name='payment_document', to='payments.document'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_subscription',
            field=models.ForeignKey(on_delete=models.SET('DELETED'), related_name='payment_user_subscription', to='subscriptions.subscription'),
        ),
    ]
