# Generated by Django 5.0.3 on 2024-03-18 15:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=users.models.increment_account_number, max_length=20, unique=True),
        ),
    ]
