# Generated by Django 5.0.3 on 2024-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_account_account_number_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.BooleanField(default=False, verbose_name='Статус привязки счёта'),
        ),
    ]
