# Generated by Django 5.0.3 on 2024-03-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='services')),
                ('login', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=1000)),
                ('conditions', models.TextField(max_length=1000)),
                ('website', models.URLField()),
                ('instruction', models.TextField(max_length=1000)),
                ('rules', models.TextField(max_length=1000)),
                ('popularity', models.IntegerField(default=0, max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category')),
            ],
        ),
    ]
