# Generated by Django 5.0.3 on 2024-03-18 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='conditions',
            field=models.TextField(max_length=1000, verbose_name='Условия'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='services/images'),
        ),
        migrations.AlterField(
            model_name='service',
            name='instruction',
            field=models.TextField(max_length=1000, verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='service',
            name='login',
            field=models.BooleanField(default=False, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Популярность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='rules',
            field=models.TextField(max_length=1000, verbose_name='Правила'),
        ),
        migrations.AlterField(
            model_name='service',
            name='website',
            field=models.URLField(verbose_name='Сайт'),
        ),
    ]
